package com.myspace.telco;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class NetElement implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Name")
	private java.lang.String name;
	@org.kie.api.definition.type.Label(value = "Parameter1")
	private java.lang.String param1;
	@org.kie.api.definition.type.Label(value = "Parameter2")
	private java.lang.String param2;
	@org.kie.api.definition.type.Label(value = "Active")
	private boolean active;

	public NetElement() {
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.String getParam1() {
		return this.param1;
	}

	public void setParam1(java.lang.String param1) {
		this.param1 = param1;
	}

	public java.lang.String getParam2() {
		return this.param2;
	}

	public void setParam2(java.lang.String param2) {
		this.param2 = param2;
	}

	public boolean isActive() {
		return this.active;
	}

	public void setActive(boolean active) {
		this.active = active;
	}
/*
	public NetElement(java.lang.String name, java.lang.String param1,
			java.lang.String param2, boolean active) {
		this.name = name;
		this.param1 = param1;
		this.param2 = param2;
		this.active = active;
	}
*/	
	public NetElement(String name) {
        this.name = name;
    }

	@Override
	public String toString() {
		return "NetElement [name=" + name + ", active=" + active + ", param1=" + param1 + ", param2=" + param2 + "]";
	}

}