package com.myspace.telco;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ProvisionResponse implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Subscription Id")
	private java.lang.String subscriptionId;
	@org.kie.api.definition.type.Label(value = "Service Name")
	private java.lang.String serviceName;
	@org.kie.api.definition.type.Label(value = "Error")
	private java.lang.Long error;

	public ProvisionResponse() {
	}

	public java.lang.String getSubscriptionId() {
		return this.subscriptionId;
	}

	public void setSubscriptionId(java.lang.String subscriptionId) {
		this.subscriptionId = subscriptionId;
	}

	public java.lang.String getServiceName() {
		return this.serviceName;
	}

	public void setServiceName(java.lang.String serviceName) {
		this.serviceName = serviceName;
	}

	public java.lang.Long getError() {
		return this.error;
	}

	public void setError(java.lang.Long error) {
		this.error = error;
	}

	public ProvisionResponse(java.lang.String subscriptionId,
			java.lang.String serviceName, java.lang.Long error) {
		this.subscriptionId = subscriptionId;
		this.serviceName = serviceName;
		this.error = error;
	}
	
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("serviceName: "); builder.append(serviceName); builder.append('\n');
		builder.append("error: "); builder.append(error); builder.append('\n');
		builder.append("serviceName: "); builder.append(serviceName); builder.append('\n');

		return builder.toString();
	}

}